<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SERIES [
    <!ELEMENT SERIES (UNIVERSAL)>
    <!ELEMENT UNIVERSAL (FBI_International)>
    <!ELEMENT FBI_International (Temporada_4)>
    <!ELEMENT Temporada_4 (Episodio+)>
    <!ELEMENT Episodio (tvg-name, Temporada, Nombre, URL)>
    <!ELEMENT tvg-name (#PCDATA)>
    <!ELEMENT Temporada (#PCDATA)>
    <!ELEMENT Nombre (#PCDATA)>
    <!ELEMENT URL (#PCDATA)>
]>
<SERIES>
    <UNIVERSAL>
        <FBI_International>
            <Temporada_4>
                <Episodio>
                    <tvg-name>FBI: INTERNATIONAL</tvg-name>
                    <Temporada>TEMPORADA 4</Temporada>
                    <Nombre>EPISODIO 5</Nombre>
                    <URL>https://example.com/episode5.mp4</URL>
                </Episodio>
                <Episodio>
                    <tvg-name>FBI: INTERNATIONAL</tvg-name>
                    <Temporada>TEMPORADA 4</Temporada>
                    <Nombre>EPISODIO 6</Nombre>
                    <URL>https://example.com/episode6.mp4</URL>
                </Episodio>
            </Temporada_4>
        </FBI_International>
    </UNIVERSAL>
</SERIES>
